/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object AndroidVersions {
    const val compileSdkVersion = 28
    const val targetSdkVersion = 28
    const val minSdkVersiosn = 20
    const val buildToolsVersion = "28.0.3"
    const val versionCode = 100
    const val versionName = "1.1.0"
}
