import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.5"
             // available: "1.3.5-1.4-M1-release-99"

    const val com_github_bumptech_glide: String = "4.11.0"

    const val com_squareup_retrofit2: String = "2.8.1"

    const val com_squareup_okhttp3: String = "4.5.0"

    const val org_jetbrains_kotlin: String = "1.3.61" // available: "1.3.72"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_android_tools_build_gradle: String = "3.6.3"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val baserecyclerviewadapterhelper: String = "3.0.0-beta11" // available: "3.0.3"

    const val swiperefreshlayout: String = "1.0.0"

    const val constraintlayout: String = "1.1.3"

    const val progressmanager: String = "1.5.0"

    const val recyclerview: String = "1.1.0"

    const val lint_gradle: String = "26.6.3"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.2.0"

    const val material: String = "1.1.0"

    const val multidex: String = "2.0.1"

    const val saf_log: String = "1.5.6"

    const val aapt2: String = "3.6.3-6040484"

    const val xui: String = "1.1.3"

    /**
     * Current version: "6.3"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
