# This is a basic workflow to help you get started with Actions
on: 
  # push: 
  #   branches:
  #     - master
  # schedule:
  #   - cron: 0 16 * * 6
  push:
  # 在指定的远程分支上，发生推送
   branches:
      - master
  # 指定文件发生修改
   paths:
      - 'config.gradle'
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build Release apk
    runs-on: ubuntu-latest
    steps:
     # 下面是多个step ，每个以“-”开头
      # step：检查分支
      - uses: actions/checkout@v1
      - name: Android Github Action
        uses: Vukan-Markovic/Github-Android-Action@1.2
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
            artifacts: "build/app/outputs/apk/debug/*.apk"
            token: ${{ secrets.CI }}

