# This is a basic workflow to help you get started with Actions
on: 
  # push: 
  #   branches:
  #     - master
  # schedule:
  #   - cron: 0 16 * * 6
  push:
  # 在指定的远程分支上，发生推送
   branches:
      - master
  # 指定文件发生修改
   paths:
      - 'config.gradle'
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build Release apk
    runs-on: ubuntu-latest
    steps:
     # 下面是多个step ，每个以“-”开头
      # step：检查分支
      - uses: actions/checkout@v1
      # step：设置jdk版本
      # step 名称
      - name: set up JDK 1.8
        # 引用公共action
        uses: actions/setup-java@v1
        with:
          # 设置参数
          java-version: 1.8
      # step：打包apk
      - name: Run Gradle command
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: assembleDebug
      # - name: Build with Gradle
        # 运行命令
      #   run: chmod +x gradlew &&./gradlew assembleDebug
            #step： 获取apk版本号
      - name: Get Apk Info
        #step id
        id: apk
        uses: JantHsueh/get-apk-info-action@master
        with:
          apkPath: app/build/outputs/apk/debug/xw-debug.apk

        #获取指定时区的时间
      - name: Get Time
        id: time
        uses: JantHsueh/get-time-action@master
        with:
          timeZone: 8



