# This is a basic workflow to help you get started with Actions
on: 
  # push: 
  #   branches:
  #     - master
  # schedule:
  #   - cron: 0 16 * * 6
  push:
  # 在指定的远程分支上，发生推送
   branches:
      - master
  # 指定文件发生修改
   paths:
      - 'config.gradle'
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build Release apk
    runs-on: ubuntu-latest
    steps:
     # 下面是多个step ，每个以“-”开头
      # step：检查分支
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      #step： 获取apk版本号
      - name: Get Apk Info
        #step id
        id: apk
        uses: JantHsueh/get-apk-info-action@master
        with:
          apkPath: app/build/outputs/apk/debug/app-debug.apk

        #获取指定时区的时间
      - name: Get Time
        id: time
        uses: JantHsueh/get-time-action@master
        with:
          timeZone: 8
